# Generated by Django 3.1.6 on 2021-02-16 12:05

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('bfg', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='time_pubication',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(max_length=255),
        ),
    ]
